# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-13 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('append_purchase_tx_fenfen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='killpredict',
            name='back_hit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='killpredict',
            name='front_hit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
