# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-13 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('append_purchase_tx_fenfen', '0002_auto_20181113_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='killpredict',
            name='back_multiple',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='killpredict',
            name='front_multiple',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
